#mail.host=172.16.4.137
#mail.port=25
#sender.username=FIA@faulukenya.com
#sender.password=
#starttls.enable = false
#mail.smtp.ehlo = false

mail.host=smtp.gmail.com
mail.port=587
sender.username=busiacounty629@gmail.com
sender.password=ovln iiys wzqq glqc
starttls.enable = true
starttls.required = true
mail.smtp.ehlo = true